spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotech
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

api.security.token.secret=${JWT_SECRET}
api.security.token.expiration-minutes=60

spring.config.import=optional:file:.env[.properties]


#swagger nao tava inciializando, forçar versao 3.0
springdoc.api-docs.version=OPENAPI_3_0

server.port=8080