-- V1: Estrutura inicial do BiblioTech
-- Baseado no schema que o Hibernate gerava via ddl-auto (agora desligado)

CREATE TABLE usuario (
                         id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome   VARCHAR(255),
                         email  VARCHAR(255),
                         cpf    VARCHAR(255),
                         senha  VARCHAR(255)
);

-- leitor herda id de usuario (estratégia JOINED / @PrimaryKeyJoinColumn)
CREATE TABLE leitor (
                        id            BIGINT NOT NULL PRIMARY KEY,
                        nacionalidade VARCHAR(255),
                        CONSTRAINT fk_leitor_usuario FOREIGN KEY (id) REFERENCES usuario (id)
);

CREATE TABLE editora (
                         id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome          VARCHAR(255),
                         nacionalidade VARCHAR(255)
);

CREATE TABLE autor (
                       id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome             VARCHAR(255),
                       nacionalidade    VARCHAR(255),
                       data_nascimento  DATE
);

CREATE TABLE livro (
                       id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       descricao        VARCHAR(255),
                       edicao           VARCHAR(255),
                       isbn             VARCHAR(255),
                       tipo             VARCHAR(255),
                       volume           VARCHAR(255),
                       paginas          INTEGER,
                       data_lancamento  DATE
);

CREATE TABLE exemplar (
                          id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          capa_dura              BOOLEAN,
                          data_compra            DATE,
                          data_impressao         DATE,
                          quantidade_disponivel  VARCHAR(255)
);

CREATE TABLE emprestimo (
                            id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);